substitutions:
  devicename: haier

esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini
  includes:
    - Haier.h

logger:
  level: DEBUG
  baud_rate: 0 #Important. You can't use serial port

wifi:
  fast_connect: true
  ssid: "smarthome"
  password: "smarthome"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $devicename
    password: "Manzes1997"

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

climate:
  - platform: custom
    lambda: |-
      auto haier = new Haier();
      App.register_component(haier);
      return {haier};
    climates:
      - name: "Haier"
